### ISSUE TITLE
SpaceProperties

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#19]
Is the property GPSAltitude duplicated by elevation? If so I would keep only one, probably GPSAltitude to comply with the naming.
Additionally the property "Location" is not needed anymore since we can describe the location with the new GPS* properties.

**Comment by mariapoveda** [comment]
Maybe @AndreaCimminoArriaga can tell if Location is needed to any other use case?

**Comment by AndreaCimminoArriaga** [comment]
Hi to all,

First of all we have two location properties core:isLocatedAt and adp:Location. I would not remove the adp:Location, which is the one I guess you are referring to. About the adp:Elevation, again I would not remove it. Following I explain myself:

* About adp:Elevation, a sensor that measures the level of the water may require this property to express the data captured about the elevation of the water regarding a reference point, e.g., the current level of the water against the level of the water yesterday. This information cannot be expressed with adp:GPSAltitude since in this context the semantics of elevation and altitude are different. This sensor can be at 1000 meters of altitude (adp:GPSAltitude) and measure an elevation of a river for instance of 15% (adp:Elevation). As a result, adp:Elevation and adp:GPSAltitude may measure different kind of metrics and this is why we should not remove the dp:Elevation.

* About locations, core:isLocatedAt is a property to describe nominal places, like "Greece", and  adp:Location can be used to specify similarly nominal places, or numerical places. The GPS properties allow only to express location in a very specific numerical way, i.e., using latitude and longitude, on the other hand adp:Location offers more flexible ways to express the location. Consider that there are more numerical specifications to convey the location of something than latitude and logitude, and this property allows to use them.

**Comment by mariapoveda** [comment]
Therefore, no if no change is need, I close the issue.
